# Generated by Django 4.2.3 on 2023-08-08 14:48

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from=models.CharField(max_length=30), unique=True),
            preserve_default=False,
        ),
    ]
