# Generated by Django 4.2.3 on 2023-08-07 13:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=50)),
                ('adress', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('fax', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('smtpserver', models.CharField(max_length=50)),
                ('smtpemail', models.CharField(max_length=150)),
                ('smtppassword', models.CharField(max_length=150)),
                ('smtpport', models.CharField(blank=True, max_length=150)),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
                ('facebook', models.CharField(max_length=130)),
                ('twitter', models.CharField(max_length=130)),
                ('instagram', models.CharField(max_length=130)),
                ('linkedin', models.CharField(max_length=130)),
                ('aboutus', ckeditor.fields.RichTextField()),
                ('references', ckeditor.fields.RichTextField()),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayir')], max_length=10)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('uptade_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
