# Generated by Django 4.2.3 on 2023-08-07 13:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='contact',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='aboutus',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='facebook',
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AlterField(
            model_name='settings',
            name='instagram',
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AlterField(
            model_name='settings',
            name='linkedin',
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AlterField(
            model_name='settings',
            name='references',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtpemail',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtppassword',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtpserver',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='settings',
            name='twitter',
            field=models.CharField(blank=True, max_length=130),
        ),
    ]
